[package]
name = "foolhtml_derive"
version = "0.0.1"
authors = ["Jonas Peter <tech@fooltopia.com>"]
edition = "2018"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"