[package]
name = "slimr_testing"
version = "0.1.0"
authors = ["Jonas Peter <hi@jonaspeter.me>"]
workspace = ".."
edition = "2021"
publish = false

[dependencies]
slimr = { path = "../slimr", version = "*" }
