[package]
name = "foolhtml_testing"
version = "0.1.0"
authors = ["Jonas Peter <tech@fooltopia.com>"]
workspace = ".."
edition = "2018"
publish = false

[dependencies]
foolhtml = { path = "../foolhtml", version = "*" }
